# Generated by Django 4.2.11 on 2026-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="transcriptions/"
                    ),
                ),
                ("original_text", models.TextField(blank=True, null=True)),
                ("formatted_text", models.TextField(blank=True, null=True)),
                ("capitalized_text", models.TextField(blank=True, null=True)),
                (
                    "custom_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Custom instructions for processing the text",
                        null=True,
                    ),
                ),
                (
                    "custom_response",
                    models.TextField(
                        blank=True, help_text="Response to custom prompt", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Image Transcription",
                "verbose_name_plural": "Image Transcriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
