# Generated by Django 4.2.29 on 2026-04-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transcriber", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="transcriptions/")),
                ("page_number", models.PositiveIntegerField(default=1)),
                ("individual_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="transcriber.imagetranscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcription Image",
                "verbose_name_plural": "Transcription Images",
                "ordering": ["page_number"],
            },
        ),
    ]
